########################################################################################
###    Jobs to test built code                                                       ###
########################################################################################

### ENVIRONMENT
.environment: &environment
  environment:
    name: '$ENVIRONMENT'
    action: prepare

.prepare-test: &prepare-test
  before_script:
    - apk add --no-cache py-pip jq
    - pip install awscli
    - eval $(aws ecr get-login --no-include-email --region eu-west-2 | sed 's|https://||')
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - export GITLAB_IMAGE="$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:${CI_COMMIT_SHA:0:8}"
    - export MOCK_IMAGE=$(aws ssm get-parameter --name "/artifact/$PRODUCT/$PIP_APPLY_MOCKS_NAME/$MOCK_IMAGE" --with-decryption --output json | jq --raw-output '.Parameter.Value')
    - echo $DT_API_TOKEN | docker login -u pik94420 --password-stdin https://pik94420.live.dynatrace.com
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

api-test:
  extends: .docker-compose-run-template
  stage: component-test
  variables:
    DOCKER_COMPOSE_FILE: "docker-compose.yml"
    DOCKER_COMPOSE_COMMAND: "--exit-code-from api-test"
    MVN_OPTS: '-Dmaven.repo.local=~/.m2/repository'
    MVN_M2: "~/.m2"
  <<: *prepare-test
  after_script:
    - docker logout
  cache:
    key: ${CI_PROJECT_NAME}
    paths:
      - ~/.m2/repository/
  artifacts:
    expire_in: 1 day
    paths:
      - target/test-reports/
    when: always
    expose_as: 'Account manager API Component Test Report'